# Generated by Django 6.0.3 on 2026-03-16 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_complexity', models.CharField(blank=True, max_length=100)),
                ('space_complexity', models.CharField(blank=True, max_length=100)),
                ('bugs_detected', models.TextField(blank=True)),
                ('optimization_suggestions', models.TextField(blank=True)),
                ('code_quality_feedback', models.TextField(blank=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='reviewer.codereview')),
            ],
        ),
    ]
