# Generated by Django 6.0.3 on 2026-03-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0002_reviewresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewresult',
            name='space_complexity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviewresult',
            name='time_complexity',
            field=models.TextField(blank=True, null=True),
        ),
    ]
