# Generated by Django 6.0.3 on 2026-03-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0003_alter_reviewresult_space_complexity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewresult',
            name='optimized_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
