# Generated by Django 6.0.3 on 2026-03-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0004_reviewresult_optimized_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewresult',
            name='dry_run',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewresult',
            name='edge_cases',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewresult',
            name='optimized_space_complexity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewresult',
            name='optimized_time_complexity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewresult',
            name='test_cases',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviewresult',
            name='bugs_detected',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviewresult',
            name='code_quality_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviewresult',
            name='optimization_suggestions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
